// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/users/create": {
    params: {};
  };
  "/admin/users/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/admin/roles": {
    params: {};
  };
  "/admin/roles/create": {
    params: {};
  };
  "/admin/permissions": {
    params: {};
  };
  "/admin/permissions/create": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/admin" | "/admin/users" | "/admin/users/create" | "/admin/users/:id/edit" | "/admin/roles" | "/admin/roles/create" | "/admin/permissions" | "/admin/permissions/create" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin";
  };
  "routes/admin/users/list.tsx": {
    id: "routes/admin/users/list";
    page: "/admin/users";
  };
  "routes/admin/users/create.tsx": {
    id: "routes/admin/users/create";
    page: "/admin/users/create";
  };
  "routes/admin/users/edit.tsx": {
    id: "routes/admin/users/edit";
    page: "/admin/users/:id/edit";
  };
  "routes/admin/roles/list.tsx": {
    id: "routes/admin/roles/list";
    page: "/admin/roles";
  };
  "routes/admin/roles/create.tsx": {
    id: "routes/admin/roles/create";
    page: "/admin/roles/create";
  };
  "routes/admin/permissions/list.tsx": {
    id: "routes/admin/permissions/list";
    page: "/admin/permissions";
  };
  "routes/admin/permissions/create.tsx": {
    id: "routes/admin/permissions/create";
    page: "/admin/permissions/create";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/users/list": typeof import("./app/routes/admin/users/list.tsx");
  "routes/admin/users/create": typeof import("./app/routes/admin/users/create.tsx");
  "routes/admin/users/edit": typeof import("./app/routes/admin/users/edit.tsx");
  "routes/admin/roles/list": typeof import("./app/routes/admin/roles/list.tsx");
  "routes/admin/roles/create": typeof import("./app/routes/admin/roles/create.tsx");
  "routes/admin/permissions/list": typeof import("./app/routes/admin/permissions/list.tsx");
  "routes/admin/permissions/create": typeof import("./app/routes/admin/permissions/create.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};